### ISSUE TITLE
How to remove transparent background ?

### ISSUE THREAD

**Issue by xenoxanite** [eylles/pywal16#25]

**Comment by eylles** [comment]
sorry for not noticing this earlier, was busy getting fired from work, regardless @xenoxanite would ya mind provide a bit more context, as in what application has transparent background or which template gets transparent background?

**Comment by xenoxanite** [comment]
> sorry for not noticing this earlier, was busy getting fired from work, regardless @xenoxanite would ya mind provide a bit more context, as in what application has transparent background or which template gets transparent background?

just delete this issue. sorry, there is a nvim plugin called pywal16-complete. i was trying to create issue there. but for my mistake i did it here.

**Comment by eylles** [comment]
got link? now i'm interested in the nvim plugin cuz i have plans to build a nvim colorscheme "proper" after pushing the next release of pywal16

**Comment by xenoxanite** [comment]
> got link? now i'm interested in the nvim plugin cuz i have plans to build a nvim colorscheme "proper" after pushing the next release of pywal16

https://github.com/uZer/pywal16.nvim
