### ISSUE TITLE
Is it possible to use it with wpgtk?

### ISSUE THREAD

**Issue by niksingh710** [eylles/pywal16#32]
using it as backend of wpgtk?

**Comment by hownioni** [comment]
I haven't tested it in a long while but last time I tried it turned out it didn't work because wpgtk couldn't handle the new flags that pywal-16 adds, i don't know if this is still the case

**Comment by niksingh710** [comment]
no issues regarding that as i am plannign to switch to pywal-16 from wpgtk.
just if it's possible to add `keyword` section where i can define a few values that will be nice.

like keywords.conf
```
font=<someFontName>
```
then a `{font}` variable is accessible like `{color0}
