### ISSUE TITLE
setup.py seems broken after setuptools 75.4.0 update

### ISSUE THREAD

**Issue by guillaumeboehm** [eylles/pywal16#81]
I'm not very well versed in python toolings so needs double checking, but it seems that the 75.4.0 setuptools update removed support for the test command.

It has been deprecated for a while and it should have been removed in a couple days I think (https://github.com/pypa/setuptools/blob/main/setuptools/command/test.py#L14) but I guess it's already gone? Though I couldn't find any clear release notes.

Anyway the setup.py script returns an `error: invalid command 'test'` on my system with setuptools v75.4.0.

They apparently recommend some other testing tooling https://setuptools.pypa.io/en/latest/deprecated/commands.html#test-build-package-and-run-a-unittest-suite.

**Comment by eylles** [comment]
thanks, will look this up as it stands the current packaging workflow doesn't really include unit testing... so doing something quick and simple for this should be no issue

**Comment by guillaumeboehm** [comment]
Oh well turns out it's quite a big part my bad.

I didn't remember that my PKGBUILD on arch is actually calling the test command directly, and thought that `test_suite` being defined caused the issue... So even with this change it still wouldn't work...

Sorry for the false negative, even though it doesn't seem to be such a bad idea to drop this parameter anyway.

So no issue anymore on my part.

**Comment by eylles** [comment]
Well is not a real false negative in that sense, i'm on devuan testing at the time so i don't got the latest python libraries, still is good to know to drop the current implementation of the test suite and begin planning a way to bring it back, as in checking which of the available options fit the pywal16 tests the best.

**Comment by eylles** [comment]
"Solved" in #82
