### ISSUE TITLE
remove the default cst="None" from colors.get call

### ISSUE THREAD

**Issue by deviantfero** [eylles/pywal16#92]
This makes the api of pywal incompatible with pywal16 as to get consistent cache filenames I'd have to pass the cst kwarg, pywal does not expose or require this keyword and neither should pywal16, just leave it empty if not provided.

https://github.com/eylles/pywal16/blob/d8fb64d9927afb287c54b852a3530f4b23608f2a/pywal/colors.py#L387-L391

produces when calling `pywal.colors.get(
        image,
        light=(is_file and light_theme),
        backend=settings.get("backend", "wal"),
        cache_dir=WPG_DIR
    )`:
```
'_home_fernando__config_wpg_wallpapers_golden_gai_JPG_9_dark_wal__None_7499119_2.0.0.json'
```

and produces when calling `cache_fname(filepath, backend, False, WPG_DIR)`:
```
'_home_fernando__config_wpg_wallpapers_golden_gai_JPG_9_dark_wal___7499119_2.0.0.json'
```

this breaks wpgtk ability to edit a theme and directly access the cache file consistently without having to check pywal's version.

**Comment by eylles** [comment]
please confirm that #93 does produce the names expected by wpgtk before i merge and cut a new release.

**Comment by deviantfero** [comment]
confirming!

**Comment by eylles** [comment]
great!
